### ISSUE TITLE
这应该是基础问题，搞不定，指导一下。谢谢

### ISSUE THREAD

**Issue by zlqlpp** [mic1on/chatGPT-web#10]
Unable to find image 'miclon/chatgpt:latest' locally
Trying to pull repository docker.io/miclon/chatgpt ... 
/usr/bin/docker-current: manifest for docker.io/miclon/chatgpt:latest not found.
See '/usr/bin/docker-current run --help'.

**Comment by mic1on** [comment]
这里是docker hub仓库地址：[miclon/chatgpt](https://hub.docker.com/repository/docker/miclon/chatgpt/tags?page=1&ordering=last_updated)

目前看来是你配置的源可能出现了问题：
参考：
https://blog.csdn.net/TommyXu8023/article/details/113291112
