### ISSUE TITLE
arm64的架构下运行，会报“exec /bin/bash: exec format error”

### ISSUE THREAD

**Issue by wangbog** [mic1on/chatGPT-web#11]
挺好的项目，写得很简单。amd64下面运行ok，但是arm64的架构下运行，报“exec /bin/bash: exec format error”。
使用“docker image inspect XXX”检查，确认了拉到的image确实是arm64版本的："Architecture": "arm64"。
看了下Dockerfile，猜测是不是用的“/miclon/py-nodejs:latest”这个原始镜像只支持amd64?
FROM registry.cn-hangzhou.aliyuncs.com/miclon/py-nodejs:latest
另外，在DockerHub上也搜不到“/miclon/py-nodejs:latest”这个镜像，github上也没看到原始的项目。这个方便共享么？

**Comment by mic1on** [comment]
已收到你的反馈，我检查一下。
