### ISSUE TITLE
香港服务器已阵亡（api域名被墙）

### ISSUE THREAD

**Issue by ranxi2001** [mic1on/chatGPT-web#17]
[root@cvm-3jg255i28a225 ~]# ping api.openai.com
PING api.openai.com (52.152.96.252) 56(84) bytes of data.

直接ping不出来，咋办哦？
大佬弄个反代教程吧，自己有节点。

**Comment by ranxi2001** [comment]
--- api.openai.com ping statistics ---
285 packets transmitted, 0 received, 100% packet loss, time 283999ms

**Comment by DKingAlpha** [comment]
这个小问题完全可以通过独立的nginx反代方法解决，不应该混在本项目内。
