### ISSUE TITLE
app.py

### ISSUE THREAD

**Issue by 7noemo** [mic1on/chatGPT-web#2]
root@22-9-10-****:~/chatGPT-web/api# python app.py
  File "app.py", line 32
    async def root():
        ^
SyntaxError: invalid syntax
root@22-9-10-****:~/chatGPT-web/api# 

32行无效语法咋处理？

docker镜像不支持
docker: no matching manifest for linux/arm64/v8 in the manifest list entries.

**Comment by mic1on** [comment]
你本地的python版本应该不是3.8+？

**Comment by mic1on** [comment]
我已经新增了[linux/arm64](https://github.com/mic1on/chatGPT-web/commit/db44778aa5ccc447a73036bdb6156e1050353fdc)架构的docker。你可以重新pull后再试。
