### ISSUE TITLE
AI回复内容是否可以加个markdown容器

### ISSUE THREAD

**Issue by zhkgo** [mic1on/chatGPT-web#20]
AI回复的内容感觉可以用markdown来解析

**Comment by louisLiu1004** [comment]
+1 能加个markdown的解析

**Comment by bcaso** [comment]
python 的代码注释中的井号好像被解析为 markdown 中的标题了。

![image](https://user-images.githubusercontent.com/32212684/229073676-9b34896e-2579-44e1-9545-d10666d1cd98.png)
