### ISSUE TITLE
建议：api.py增加对http_proxy的代理判断。

### ISSUE THREAD

**Issue by hoochanlon** [mic1on/chatGPT-web#23]
我在做公网IP测试访问时，因为没有域名，而https证书是和域名进行绑定的，直接使用https+ip地址证书就会校验失败，所以无法通过https+ip地址访问后台服务。就算开了代理，或proxychain这种终端全局代理，也是无济于事。

 #17  的问题呢，可以用 httping 工具做测试，看看代理是否生效，再综合分析原因，校对故障。

https://github.com/mic1on/chatGPT-web/blob/71ae0a88887f4f918b52143cddd818e5657a34d9/api/api.py#L5-L7

以上都是我个人的理解啦，如有不对，还请作者及大家共同指正。

**Comment by nowanti** [comment]
你这个问题是证书和IP不匹配导致校验失败，跟你是否使用全局代理没有任何关系。两个问题互相矛盾，建议直接用IP，不要证书。否则请关联域名。

**Comment by hoochanlon** [comment]
> 你这个问题是证书和IP不匹配导致校验失败，跟你是否使用全局代理没有任何关系。两个问题互相矛盾，建议直接用IP，不要证书。否则请关联域名。

了解，谢谢。被弄糊涂了。

顺带关联“关于访问openai接口网络不通的解决方案”：https://github.com/zhayujie/chatgpt-on-wechat/issues/351#issue-1609830709
