### ISSUE TITLE
不通了，是必须要VPN了吗？

### ISSUE THREAD

**Issue by xiadongxiang** [mic1on/chatGPT-web#24]
<img width="1512" alt="CleanShot 2023-03-07 at 18 31 40@2x" src="https://user-images.githubusercontent.com/15646003/223396781-af2ad7d7-5ee0-4f9b-b5cd-b4a87e719b40.png">

**Comment by hooli67** [comment]
+1

**Comment by Gabriel0402** [comment]
+1

**Comment by MKDJOJO** [comment]
+1

**Comment by hooli67** [comment]
在clash下面用也不行，在clash下可以上chatgpt，但是运行这个docker加上proxy就是不行，显示同样的错误

**Comment by mic1on** [comment]
代理相关问题移步：[proxy.md](https://github.com/mic1on/chatGPT-web/blob/main/PROXY.md)
