### ISSUE TITLE
本地部署的问题 没有dist文件夹啊

### ISSUE THREAD

**Issue by slikyo** [mic1on/chatGPT-web#31]
你好 ，这个项目非常棒，感谢大佬开源分享。
我想本地搭建一下服务，并做一些修改，比如增加自定义system prompt，temperature，增加socks代理等。
但是这一步就没法继续下去了，
cp -r web/dist api/dist
web下面没有dist文件夹。
直接run的话会提示以下错误
chatGPT-web\api\dist\assets' does not exist 求教

**Comment by mic1on** [comment]
你好，这个项目是分前后端的，web目录下是前端代码，dist目录是需要前端代码build后才会产生的。

你可以在前端项目中，运行：
> pnpm run build
来运行前端的构建，随后会在前端目录下，产生dist目录。

**Comment by slikyo** [comment]
我感觉我问了个弱智问题，感谢！！！
