### ISSUE TITLE
代理设置与文档/惯用法不符

### ISSUE THREAD

**Issue by Hivoodoo** [mic1on/chatGPT-web#34]
https://github.com/mic1on/chatGPT-web/blob/24cf0ce7cc890cc3cd14f97f31679dfdfdad24a2/api/api.py#L7
这里不需要加协议名, 应改为  `PROXIES = proxy`
<img width="890" alt="image" src="https://user-images.githubusercontent.com/8285370/226198315-b05db2f1-3b0e-4e44-9c10-f80cd6339f6d.png">

**Comment by mic1on** [comment]
我看[httpx文档](https://www.python-httpx.org/advanced/#example)是显示需要的
