### ISSUE TITLE
时常回复“我不知道你在说什么”

### ISSUE THREAD

**Issue by zwfpro** [mic1on/chatGPT-web#4]
如图：![案例](https://imgse.com/i/pSTDLoF)

**Comment by mic1on** [comment]
是的，在超过`60s`未返回数据时会回复：我不知道你在说什么

**Comment by 7noemo** [comment]
> 是的，在超过`60s`未返回数据时会回复：我不知道你在说什么

不能在vps云服务器上部署吗？
