### ISSUE TITLE
请问下key需要在代码哪里更换呢？

### ISSUE THREAD

**Issue by lmuiotctf** [mic1on/chatGPT-web#5]
请问下key需要在代码哪里更换呢？

**Comment by mic1on** [comment]
Linux环境是：export API_KEY=xxxxxx

docker环境是： -e API_KEY=xxxx

**Comment by lmuiotctf** [comment]
能否加入下一个入口自定义填入key?这样每个人用key就可以直接用

**Comment by mic1on** [comment]
项目的逻辑是开发者为这个服务提供一个KEY，然后开启服务后给自己或者其他人使用。所以前端也没有Key的查看与修改功能。

**Comment by mic1on** [comment]
你说的这个我会采纳，那就是后端不提供KEY了，让使用的人在前端输入key，然后直接使用

**Comment by lmuiotctf** [comment]
对的，直接前端输入即可，这样会好点

**Comment by mic1on** [comment]
[前端允许自定义](https://github.com/mic1on/chatGPT-web/commit/4df0a8b233c7bf2ab4faedcdc1419c6494317d3c)
