### ISSUE TITLE
能不能添加代理上去？

### ISSUE THREAD

**Issue by ghost** [mic1on/chatGPT-web#6]
是否可以添加代理

**Comment by mic1on** [comment]
您指的代理是后端访问API时的代理吗

**Comment by qingfusheng** [comment]
你好，如果是后端访问GPT3的代理的话，可以去参考[httpx添加代理](https://www.w3cschool.cn/httpx/httpx-http-proxying.html)中的方法，因为api.py中对后端的请求是通过httpx来做的。

**Comment by Sug2077** [comment]
> 你好，如果是后端访问GPT3的代理的话，可以去参考[httpx添加代理](https://www.w3cschool.cn/httpx/httpx-http-proxying.html)中的方法，因为api.py中对后端的请求是通过httpx来做的。

测试可用

**Comment by xyb** [comment]
@maxage 在命令行中启动前，可以使用 `export https_proxy=host:port` 的方式设置代理的环境变量。如果是用 docker，可以添加参数 `-e` 来设置环境变量，例如：`docker run --name chatgpt -d -p 8000:8000 -e API_KEY=xxxxxx -e "https_proxy=host:port" miclon/chatgpt:latest`。

**Comment by hoochanlon** [comment]
> @maxage 在命令行中启动前，可以使用 `export https_proxy=host:port` 的方式设置代理的环境变量。如果是用 docker，可以添加参数 `-e` 来设置环境变量，例如：`docker run --name chatgpt -d -p 8000:8000 -e API_KEY=xxxxxx -e "https_proxy=host:port" miclon/chatgpt:latest`。

赞同，docker确实得另加才行。
