### ISSUE TITLE
api通病，不能记住上一次的内容

### ISSUE THREAD

**Issue by 18y** [mic1on/chatGPT-web#7]
不能记住上一次的内容，这个不知道能不能解决...

**Comment by qingfusheng** [comment]
也不能说是API的通病吧，因为GPT3的那个模型（比如达芬奇的那个模型），使用的时候好像都是，“Human:~~~.AI:~~~.Human:~~~.AI:~~~.”的方式，就是你在调用接口的时候需要把前面的聊天记录都post上去，这样模型才能够通过上下文环境理解。
代码示例：
![image](https://user-images.githubusercontent.com/61900087/219873137-74413b3d-4122-4e4b-9374-d4252b5620c6.png)

效果就像这样：
![QQ截图20230218230628](https://user-images.githubusercontent.com/61900087/219873092-f6ed28b1-56f2-4c97-9d05-653e02f78a3c.png)

**Comment by qingfusheng** [comment]
我曾经也考虑过将这个加入到接口中，但是这样的话必须要考虑text的创建时机和销毁时机（我觉得应该跟前端有关，就像是你在刷新页面的时候将聊天信息清除的同时也将text重新置为0，有点类似于缓存的创建时机和销毁时机的问题），因为我对前端不是很了解，所以没有想到比较好的处理方法。但是我觉得存储上下文信息的这个function必须要放到前端（而且必要时还是限制token大小吧，不然随着聊天，text会越来越大）。

**Comment by qingfusheng** [comment]
要限制text的大小，因为GPT3的接口并不是免费的。

**Comment by 18y** [comment]
感谢回复~，现在的收费方式我有点迷

**Comment by mic1on** [comment]
[解决连续对话](https://github.com/mic1on/chatGPT-web/commit/dbdcc0f95dc0f51b9d5ea16f40e54b447e239688)
